var xm_callback=null,xm_haveAccount=!1;function HandleLoad(){LoadLocalizedStrings();var a=chrome.extension.getBackgroundPage().Xmarks.Settings.GetWindowParams();a&&(xm_haveAccount=a.have_account,xm_callback=a.callback);xm_haveAccount?document.getElementById("default-check-have-account").checked=!0:document.getElementById("default-check-no-account").checked=!0}
function LoadLocalizedStrings(){document.title=chrome.i18n.getMessage("firsttimesync_title");document.getElementById("fts-message-ready").innerHTML=chrome.i18n.getMessage("firsttimesync_ready");document.getElementById("fts-message-perform").innerHTML=chrome.i18n.getMessage("firsttimesync_perform");document.getElementById("fts-message-merge-local").innerHTML=chrome.i18n.getMessage("firsttimesync_merge_local");document.getElementById("fts-message-merge-server").innerHTML=chrome.i18n.getMessage("firsttimesync_merge_server");
document.getElementById("fts-message-download").innerHTML=chrome.i18n.getMessage("firsttimesync_download");document.getElementById("fts-message-upload").innerHTML=chrome.i18n.getMessage("firsttimesync_upload");document.getElementById("button-cancel").value=chrome.i18n.getMessage("dialog_cancel");document.getElementById("button-change").value=chrome.i18n.getMessage("dialog_change");document.getElementById("button-sync").value=chrome.i18n.getMessage("dialog_sync");document.getElementById("button-ok").value=
chrome.i18n.getMessage("dialog_ok")}
function HandleAction(a){if("ok"==a){a=document.forms[0].synctype;for(var c="merge-server",b=0;b<a.length;b++)a[b].checked&&(c=a[b].value);var d;"merge-local"==c?a=chrome.i18n.getMessage("firsttimesync_merge_local_description"):"merge-server"==c?a=chrome.i18n.getMessage("firsttimesync_merge_server_description"):"download"==c?(a=chrome.i18n.getMessage("firsttimesync_download_description"),d=chrome.i18n.getMessage("firsttimesync_download_warning")):(a=chrome.i18n.getMessage("firsttimesync_upload_description"),d=
chrome.i18n.getMessage("firsttimesync_upload_warning"));document.getElementById("info").innerHTML=a;d&&xm_haveAccount?(document.getElementById("note").innerHTML=d,document.getElementById("note").style.display="block"):document.getElementById("note").style.display="none";document.getElementById("section-overview").style.display="block";document.getElementById("section-change").style.display="none";document.getElementById("button-change").style.display=xm_haveAccount?"inline":"none";document.getElementById("button-sync").style.display=
"inline";document.getElementById("button-ok").style.display="none"}else if("change"==a)document.getElementById("section-overview").style.display="none",document.getElementById("section-change").style.display="block",document.getElementById("button-change").style.display="none",document.getElementById("button-sync").style.display="none",document.getElementById("button-ok").style.display="inline";else if("sync"==a){a=document.forms[0].synctype;c="";for(b=0;b<a.length;b++)a[b].checked&&(c=a[b].value);
xm_callback(top,{synctype:c})}}
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){HandleLoad();HandleAction("ok")});window.addEventListener("unload",function(){HandleAction("cancel")});document.getElementById("button-cancel").addEventListener("click",function(){window.close()});document.getElementById("button-change").addEventListener("click",function(){HandleAction("change")});document.getElementById("button-sync").addEventListener("click",function(){HandleAction("sync")});document.getElementById("button-ok").addEventListener("click",
function(){HandleAction("ok")})});
