function EnumerateDeletedNodes(a,b,c){function e(a){c.Node(a,!1,!0)||h.push(a);a=b.Node(a);a.children&&a.children.forEach(function(a){e(a)})}var h=null;a.set.forEach(function(a){"delete"==a.action&&(a.deleted=[],h=a.deleted,e(a.nid))})}function CleanDeletedNodes(a){a.set.forEach(function(a){"delete"==a.action&&delete a.deleted;delete a.fixed})}function CleanServerMoves(a,b){a.set.forEach(function(a){"move"==a.action&&a.args.pnid==b.Node(a.nid).pnid&&(a.action="reorder",delete a.args.pnid)})}
function CombinePrePost(a){a.set=a.pre.concat(a.set).concat(a.post);delete a.pre;delete a.post}function OpenConflictDialog(a,b){var c=Cc["@mozilla.org/appshell/window-mediator;1"].getService().QueryInterface(Ci.nsIWindowMediator),e=c.getMostRecentWindow("foxmarks:progress");if(!e&&(e=c.getMostRecentWindow(null),!e))return null;c={};e.openDialog(a,"_blank","chrome,dialog,modal,centerscreen",c,b);return c.selection}
var DETECTORS={insert_insert:function(a,b,c,e){if(a.nid==b.nid){var h=[];forEach(a.args,function(a,c){b.args[c]&&(!DETECTORS.HARMLESS_ATTRS[c]&&a!=b.args[c])&&h.push(c+":"+a)});forEach(b.args,function(b,c){a.args[c]&&(!DETECTORS.HARMLESS_ATTRS[c]&&b!=a.args[c])&&h.push(c+":"+b)});if(h.length){var t=c.Node(a.nid);e=e.Node(b.nid);c=c.handleNidConflict(t,e,h);showedUI=!0;if("local"==c)return["overwrite","local"];if("server"==c)return["overwrite","server"];if("same"==c)return["drop","both"];throw 2;}return["drop",
"both"]}return a.args.pnid==b.args.pnid&&a.args.bnid==b.args.bnid?["transit","server"]:null},insert_move:function(a,b){return a.args.pnid!=b.args.pnid&&a.args.bnid==b.nid?["nextsib","left"]:a.nid!=b.nid&&a.args.pnid==b.args.pnid&&a.args.bnid==b.args.bnid?["transit","server"]:null},insert_reorder:function(a,b,c,e){return a.args.pnid==e.Node(b.nid).pnid&&a.args.bnid==b.args.bnid&&!b.fixed?["transit","server"]:a.args.pnid==e.Node(b.nid).pnid&&a.args.bnid==b.nid?["nextsib","left"]:null},insert_update:function(){return null},
delete_insert:function(a,b){return 0<=a.deleted.indexOf(b.args.bnid)?["nextsib","right"]:0<=a.deleted.indexOf(b.args.pnid)?["delinsert","left"]:null},delete_delete:function(a,b){return a.nid==b.nid?["drop","both"]:0<=a.deleted.indexOf(b.nid)?["drop","right"]:0<=b.deleted.indexOf(a.nid)?["drop","left"]:null},delete_move:function(a,b){return 0<=a.deleted.indexOf(b.args.bnid)?["nextsib","right"]:0<=a.deleted.indexOf(b.nid)?["drop","right"]:0<=a.deleted.indexOf(b.args.pnid)?["delmovein","left"]:null},
delete_reorder:function(a,b){return 0<=a.deleted.indexOf(b.nid)?["drop","right"]:a.nid==b.args.bnid?["nextsib","right"]:null},delete_update:function(a,b){if(0<=a.deleted.indexOf(b.nid)){for(var c in b.args)if(b.args.hasOwnProperty(c)&&!DETECTORS.HARMLESS_ATTRS[c])return["delupdate","left"];return["drop","right"]}return null},move_move:function(a,b,c,e){if(a.args.pnid==b.args.pnid){if(a.nid==b.nid)return a.args.bnid==b.args.bnid?["drop","both"]:["drop","server"];if(a.args.bnid==b.args.bnid)return["transit",
"server"]}else{if(a.nid==b.nid)return c.Node(a.nid),c.Node(a.args.pnid),e.Node(b.args.pnid),showedUI=!0,["drop","server"];if(a.nid==b.args.bnid)return["nextsib","right"];if(a.args.bnid==b.nid)return["nextsib","left"]}return null},move_reorder:function(a,b,c,e){return a.nid==b.nid?["drop","right"]:a.nid==b.args.bnid&&a.args.pnid!=e.Node(b.nid).pnid&&!b.fixed?["nextsib","right"]:a.args.pnid==e.Node(b.nid).pnid&&a.args.bnid==b.args.bnid&&!b.fixed?["transit","server"]:null},move_update:function(){return null},
reorder_reorder:function(a,b,c,e){return c.Node(a.nid).pnid!=e.Node(b.nid).pnid?null:a.nid==b.nid?a.args.bnid==b.args.bnid?a.fixed?null:["drop","both"]:["drop","server"]:a.nid==b.args.bnid&&!b.fixed?["commutereorder","left"]:a.args.bnid==b.nid&&!a.fixed?["commutereorder","right"]:null},reorder_update:function(){return null},HARMLESS_ATTRS:{created:!0,visited:!0,modified:!0,"private":!0,icon:!0},update_update:function(a,b,c,e){if(a.nid==b.nid){var h=[];forEach(a.args,function(a,c){b.args[c]&&(!DETECTORS.HARMLESS_ATTRS[c]&&
a!=b.args[c])&&h.push(c)});if(1==h.length&&"tags"==h[0]||a.nid==NODE_ROOT)return["drop","server"];if(h.length){a=c.Node(a.nid);e=e.Node(b.nid);c=c.handleNidConflict(a,e,h);showedUI=!0;if("local"==c)return["drop","server"];if("server"==c)return["drop","local"];if("same"==c)return["drop","both"];throw 2;}return null}}};
function Synchronize(a,b,c,e,h,t){function s(a){switch(a){case "both":b.drop(g);c.drop(j);g-=1;n=!0;break;case "local":b.drop(g);g-=1;n=!0;break;case "server":c.drop(j);j-=1;break;default:throw Error("Unknown sync parameter "+f[1]);}}EnumerateDeletedNodes(b,a,e);EnumerateDeletedNodes(c,a,h);b.pre=[];b.post=[];c.pre=[];c.post=[];for(var u=0,v={},g=0;g<b.set.length;++g)for(var l=b.set[g],f=null,n=!1,j=0;j<c.set.length;++j){sc=c.set[j];var d=DETECTORS[l.action+"_"+sc.action];if(d){try{f=d(l,sc,e,h,!1)}catch(w){throw Xmarks.LogWrite("Synchronize: failed processing "+
JSON.stringify(l)+", "+JSON.stringify(sc)),Xmarks.LogWrite("Error is "+JSON.stringify(w)+" e:"+w),w;}if(!f)continue;"left"==f[1]?f[1]="local":"right"==f[1]&&(f[1]="server")}else{d=DETECTORS[sc.action+"_"+l.action];if(!d)throw Error("Couldn't find conflict detector for "+l.action+" : "+sc.action);try{f=d(sc,l,h,e,!0)}catch(x){throw Xmarks.LogWrite("Synchronize: failed processing (reversed) "+JSON.stringify(sc)+", "+JSON.stringify(l)),Xmarks.LogWrite("Error is "+JSON.stringify(x)+" e:"+x),x;}if(!f)continue;
"left"==f[1]?f[1]="server":"right"==f[1]&&(f[1]="local")}v[f[0]]=(v[f[0]]||0)+1;Xmarks.LogWrite(">>> Sync: Executing "+f[0]+"("+f[1]+") on "+JSON.stringify(l)+" vs. "+JSON.stringify(sc));switch(f[0]){case "drop":s(f[1]);break;case "overwrite":switch(f[1]){case "local":c.drop(j);j-=1;b.set[g].action="update";b.set[g].args.bnid=void 0;b.set[g].args.pnid=void 0;break;case "server":b.drop(g);g-=1;c.set[j].action="update";c.set[j].args.bnid=void 0;c.set[j].args.pnid=void 0;break;default:throw Error("Unknown sync parameter "+
f[1]);}break;case "transit":switch(f[1]){case "local":l.args.bnid=sc.nid;g-=1;n=!0;break;case "server":sc.args.bnid=l.nid;g=-1;n=!0;break;default:throw Error("Uknown sync parameter "+f[1]);}break;case "nextsib":switch(f[1]){case "local":l.args.bnid=e.NextSibling(l.args.bnid,a);g-=1;n=!0;break;case "server":sc.args.bnid=h.NextSibling(sc.args.bnid,a);g=-1;n=!0;break;default:throw Error("Unknown sync parameter "+f[1]);}break;case "delinsert":var k=d=null;"server"==f[1]?(d=l,k=c):(d=sc,k=b);var m=NearestAncestor(d.args.pnid,
a,e,h);d.args.pnid=m;d.args.bnid=null;k.pre.push(new Command("move",d.nid,{pnid:m}));d=new Command("reorder",d.nid,{bnid:null});b.post.push(d);c.post.push(d);g=-1;n=!0;break;case "delmovein":k=d=null;"server"==f[1]?(d=l,k=c):(d=sc,k=b);m=NearestAncestor(d.args.pnid,a,e,h);d.args.pnid=m;d.args.bnid=null;k.pre.push(new Command("move",d.nid,{pnid:m}));d=new Command("reorder",d.nid,{bnid:null});b.post.push(d);c.post.push(d);g=-1;n=!0;break;case "delmoveout":var p=m=k=d=null,q=null,r=null,y=null,z=0;"server"==
f[1]?(d=l,k=b,m=g,p=e,q=sc,r=h,y=c,z=j):(d=sc,k=c,m=j,p=h,q=l,r=e,y=b,z=g);k.set.splice(m,1);ResurrectNodes(d.nid,a,p,r,k,m,q,y,z,d.args.bnid);g=-1;n=!0;break;case "delupdate":p=m=k=d=null;r=q=0;"server"==f[1]?(d=l,k=b,updateNS=e,m=sc,p=h,delCS=c,q=j,r=g):(d=sc,k=c,updateNS=h,m=l,p=e,delCS=b,q=g,r=j);k=ResurrectNodes(d.nid,a,updateNS,p,k,r,m,delCS,q,null);k!=updateNS.Node(d.nid).pnid&&delCS.pre.push(new Command("move",d.nid,{pnid:k}));updateNS.OrderIsImportant()&&(d=new Command("reorder",d.nid,{bnid:null}),
b.post.push(d),c.post.push(d));g=-1;n=!0;break;case "commutereorder":d=f[1];k="local"==d?sc:l;m="local"==d?b.set:c.set;p="local"==d?g:j;k.fixed=!0;if(null==("local"==d?e:h).Node(k.nid,!1,!0))s("local"==d?"server":"local");else{Xmarks.LogWrite("Duplicating command from "+d+": "+JSON.stringify(k));for(p++;p<m.length&&m[p].fixed;++p);m.splice(p,0,k);g=-1;n=!0}break;default:throw Error("Unknown sync operator "+f[0]);}if(n){u+=1;if(2E3<=u)throw 1013;break}}CleanDeletedNodes(b);CleanDeletedNodes(c);CombinePrePost(b);
CombinePrePost(c);CleanServerMoves(b,h);t(b,c,v,!1)}function NearestAncestor(a,b,c,e){for(;a;){var h=b.Node(a,!1,!0);if(!h)throw Error("NearestAncestor failed accessing "+a);if(c.Node(a,!1,!0)&&e.Node(a,!1,!0))return a;a=h.pnid}throw"Couldn't find a common ancestor!";}
function ResurrectNodes(a,b,c,e,h,t,s,u,v,g){for(var l=[a],f=null;l.length;){a=l.shift();var n=b.Node(a),j=c.Node(a,!1,!0),d=s.deleted.indexOf(a);if(0<=d&&j&&(!f||j.pnid==n.pnid))j=j.GetSafeAttrs(),f||(f=NearestAncestor(j.pnid,b,c,e),j.pnid=f,g&&(j.bnid=g)),h.set.splice(t++,0,new Command("insert",a,j)),forEach(h.set,function(b,c){"update"==b.action&&b.nid==a&&h.drop(c)}),0<=d&&s.deleted.splice(d,1),n.children&&forEach(n.children,function(a){l.push(a)})}s.deleted.length||u.drop(v);return f};
