function LoadUI(){var a=chrome.extension.getBackgroundPage();document.getElementById("version-string").innerHTML=chrome.i18n.getMessage("settings_version_string",[a.Xmarks.Settings.Get("version")])}function TriggerAction(a,b){var c=chrome.extension.getBackgroundPage(),d={};b&&(d.dataType=b);c.HandleAction(a,d)}function HighlightCategory(a){"category"==a.className&&(a.className="category-highlight")}function UnhighlightCategory(a){"category-highlight"==a.className&&(a.className="category")}
function FormatDateString(a,b){var c=new Date;c.setTime(a);var d=[chrome.i18n.getMessage("settings_sunday"),chrome.i18n.getMessage("settings_monday"),chrome.i18n.getMessage("settings_tuesday"),chrome.i18n.getMessage("settings_wednesday"),chrome.i18n.getMessage("settings_thursday"),chrome.i18n.getMessage("settings_friday"),chrome.i18n.getMessage("settings_saturday")],e=[chrome.i18n.getMessage("settings_january"),chrome.i18n.getMessage("settings_february"),chrome.i18n.getMessage("settings_march"),chrome.i18n.getMessage("settings_april"),
chrome.i18n.getMessage("settings_may"),chrome.i18n.getMessage("settings_june"),chrome.i18n.getMessage("settings_july"),chrome.i18n.getMessage("settings_august"),chrome.i18n.getMessage("settings_september"),chrome.i18n.getMessage("settings_october"),chrome.i18n.getMessage("settings_november"),chrome.i18n.getMessage("settings_december")],d=d[c.getDay()];b||(d=d.substr(0,3));var e=d+", "+e[c.getMonth()]+" "+c.getDate(),d=c.getHours(),f=chrome.i18n.getMessage("settings_time_am");0==d?d=12:12==d?f=chrome.i18n.getMessage("settings_time_pm"):
12<d&&(d-=12,f=chrome.i18n.getMessage("settings_time_pm"));c=c.getMinutes();10>c&&(c="0"+c);return e+(" ("+d+":"+c+f+")")}
function InitCategory(a){var b=chrome.extension.getBackgroundPage();if("category-general-section"==a){a=b.Xmarks.Settings.GetUserSettings();a.username?(document.getElementById("subsection-account-userinfo").innerHTML=chrome.i18n.getMessage("settings_syncing_as",[a.username]),document.getElementById("subsection-account-authenticate").value=chrome.i18n.getMessage("settings_sign_out")):(document.getElementById("subsection-account-userinfo").innerHTML=chrome.i18n.getMessage("settings_not_signed_in"),
document.getElementById("subsection-account-authenticate").value=chrome.i18n.getMessage("settings_sign_in"));if(a=a.lastsync||0){var c=b.GetStatusDetails(),d=chrome.extension.getURL("images/status-"+c.syncStatus+".png");document.getElementById("subsection-current-status").innerHTML='<img src="'+d+'" /> '+c.syncText;b.Xmarks.Settings.Get("sync-error")?(document.getElementById("subsection-current-status-details").innerHTML=b.Xmarks.Settings.Get("sync-error")+' <a href="http://helpdesk.xmarks.com/troubleshooting/chrome-troubleshooting/" target="_blank">'+
chrome.i18n.getMessage("settings_get_help")+"</a>.",document.getElementById("subsection-current-status-details").style.display="block"):document.getElementById("subsection-current-status-details").style.display="none"}else document.getElementById("subsection-current-status").innerHTML='<img src="images/status-none.png" /> '+chrome.i18n.getMessage("settings_has_not_synced");a?(document.getElementById("subsection-current-last-sync").innerHTML=chrome.i18n.getMessage("settings_last_sync")+": "+FormatDateString(a,
!1),document.getElementById("subsection-current-last-sync").style.display="block"):document.getElementById("subsection-current-last-sync").style.display="none"}else"category-sync-section"==a?(document.getElementById("subsection-types-bookmarks").checked="true"==b.Xmarks.Settings.Get("sync-type-bookmarks","true"),document.getElementById("subsection-types-tabs").checked="true"==b.Xmarks.Settings.Get("sync-type-tabs","true"),document.getElementById("subsection-options-autosync").checked="true"==b.Xmarks.Settings.Get("enable-auto-sync",
"true"),UpdateComputerNameDisplay()):"category-profiles-section"==a?(a=b.Xmarks.Settings.GetUserSettings(),a.profilename&&(document.getElementById("cur-profile-name").innerHTML=a.profilename.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"))):"category-advanced-section"==a&&(a=parseInt(b.Xmarks.Settings.Get("securityLevel",1)),0!=a&&(document.getElementById("encryption-setting").selectedIndex=-1==a?0:2),document.getElementById("message-upload-bookmarks").disabled="false"==b.Xmarks.Settings.Get("sync-type-bookmarks",
"true"),document.getElementById("message-download-bookmarks").disabled="false"==b.Xmarks.Settings.Get("sync-type-bookmarks","true"),b=b.Xmarks.Settings.Get("disableLogging","false"),document.getElementById("enable-logging").checked="true"==b?!1:!0,document.getElementById("logging-info").style.display="true"==b?"none":"block")}function CloseAndTogglePw(){$("#modaldialog").dialog("close")}
function LoadCategory(a){if("category-selected"!=a.className){for(var b=document.getElementById("all-categories"),c=0;c<b.children.length;c++)"category-selected"==b.children[c].className&&(b.children[c].className="category");b=document.getElementById("all-sections");for(c=0;c<b.children.length;c++)b.children[c].style.display="none";a.className="category-selected";a=a.id+"-section";InitCategory(a);document.body.setAttribute("current-ui-section",a);document.getElementById(a).style.display="block"}}
function PreviewBookmarks(){var a=document.getElementById("restore-selectbox");chrome.tabs.create({url:"http://my.xmarks.com/bookmarks/view/"+a.options[a.selectedIndex].value})}function ToggleAuth(){chrome.extension.getBackgroundPage().ToggleUserAuthentication(function(){InitCategory("category-general-section")})}function RunSetupWizard(){chrome.extension.getBackgroundPage().StartSetupWizard()}
function HandleLoggingChange(){var a=chrome.extension.getBackgroundPage(),b=document.getElementById("enable-logging").checked;a.Xmarks.Settings.Set("disableLogging",b?"false":"true",!0);document.getElementById("logging-info").style.display=b?"block":"none"}function VisitMyXmarks(){window.open("http://my.xmarks.com/?mode=profiles","_blank")}function ShowProfilesWindow(){chrome.extension.getBackgroundPage().ShowChangeSyncProfilesWindow()}
function HandleEncryptionChange(a){chrome.extension.getBackgroundPage().Xmarks.Settings.Set("securityLevel",parseInt(a.options[a.selectedIndex].value),!0)}function HandleSyncTypeBookmarksChange(){chrome.extension.getBackgroundPage().Xmarks.Settings.Set("sync-type-bookmarks",document.getElementById("subsection-types-bookmarks").checked,!0)}
function HandleComputerNameChange(){chrome.extension.getBackgroundPage().Xmarks.Settings.Set("sync-computer-name",document.getElementById("computer-name").value,!0)}function HandleSyncTypeTabsChange(){chrome.extension.getBackgroundPage().Xmarks.Settings.Set("sync-type-tabs",document.getElementById("subsection-types-tabs").checked,!0);UpdateComputerNameDisplay()}
function UpdateComputerNameDisplay(){if(document.getElementById("subsection-types-tabs").checked){var a=chrome.extension.getBackgroundPage().Xmarks.Settings.Get("sync-computer-name",chrome.i18n.getMessage("settings_default_computer_name"));document.getElementById("computer-name").value=a;document.getElementById("tabs-computer-name").style.display="block"}else document.getElementById("tabs-computer-name").style.display="none"}
function HandleAutoSyncChange(){chrome.extension.getBackgroundPage().Xmarks.Settings.Set("enable-auto-sync",document.getElementById("subsection-options-autosync").checked,!0)}
function HandleSyncStatusChange(a){InitCategory(document.body.getAttribute("current-ui-section"));if(a.syncInfo){for(var b="",c=0;c<a.syncInfo.processed.length;c++)b+='<div style="margin: 5px 15px 0 15px; text-transform: capitalize; font-size: 8pt"><span style="font-weight: bold">'+a.syncInfo.processed[c].type+":</span> "+a.syncInfo.processed[c].status+"</div>";for(c=0;c<a.syncInfo.toProcess.length;c++){var d="Pending...";0==c&&(d="In progress...");b+='<div style="margin: 5px 15px 0 15px; text-transform: capitalize; font-size: 8pt"><span style="font-weight: bold">'+
a.syncInfo.toProcess[c].type+":</span> "+d+"</div>"}a.syncInfo.toProcess.length?($("#modaldialog").html(chrome.i18n.getMessage("bg_currently_syncing")+'<div style="text-align: center; margin: 1em 0"><img src="images/loading-bar.gif" /></div>'+b),$("#modaldialog").dialog("option","buttons",{}),$("#modaldialog").dialog("open")):($("#modaldialog").dialog("close"),"false"==chrome.extension.getBackgroundPage().Xmarks.Settings.Get("auto-sync","false")&&($("#modaldialog").html('<div><span style="text-transform: capitalize">'+
a.syncInfo.action+"</span> complete.</div>"+b),$("#modaldialog").dialog("option","buttons",{Ok:function(){$(this).dialog("close")}}),$("#modaldialog").dialog("open")))}}function ConfirmUpload(a){$("#modaldialog").html("Are you sure you want to overwrite your saved "+a+" with the ones in this browser?");$("#modaldialog").dialog("option","buttons",{Cancel:function(){$(this).dialog("close")},Upload:function(){$(this).dialog("close");TriggerAction("upload",a)}});$("#modaldialog").dialog("open")}
function ConfirmDownload(a){$("#modaldialog").html("Are you sure you want to overwrite your browser's "+a+" with the ones you have saved on our servers?");$("#modaldialog").dialog("option","buttons",{Cancel:function(){$(this).dialog("close")},Download:function(){$(this).dialog("close");TriggerAction("download",a)}});$("#modaldialog").dialog("open")}function RepairNow(a){TriggerAction("repair",a)}
function HandleLoad(){$("#modaldialog").dialog({autoOpen:!1,modal:!0,title:"Xmarks"});LoadLocalizedStrings();var a=chrome.extension.getBackgroundPage();if(!a||!a.Xmarks)document.getElementById("notready-notice").style.display="block",document.getElementById("settings-box").style.display="none";else{var b="category-general";0<location.href.indexOf("?")&&(b=location.href.substring(location.href.indexOf("?")+1));"true"==a.Xmarks.Settings.Get("upgrade-run","false")?(a.Xmarks.Settings.Set("upgrade-run",
"false"),document.getElementById("upgrade-notice").style.display="block","true"==a.Xmarks.Settings.Get("major-upgrade-run","false")&&(a.Xmarks.Settings.Set("major-upgrade-run","false"),a.ShowSuccessPage("upgrade",!1))):document.getElementById("upgrade-notice").style.display="none";LoadUI();LoadCategory(document.getElementById(b))}}
function LoadLocalizedStrings(){document.title=chrome.i18n.getMessage("settings_title");document.getElementById("message-update").innerHTML=chrome.i18n.getMessage("settings_updated",['<a href="https://buy.xmarks.com/notes.php" target="_blank">',"</a>"]);document.getElementById("message-not-loaded").innerHTML=chrome.i18n.getMessage("settings_not_loaded");document.getElementById("message-status-title").innerHTML=chrome.i18n.getMessage("settings_status_title");document.getElementById("message-sync-title").innerHTML=
chrome.i18n.getMessage("settings_sync_title");document.getElementById("message-profiles-title").innerHTML=chrome.i18n.getMessage("settings_profiles_title");document.getElementById("message-advanced-title").innerHTML=chrome.i18n.getMessage("settings_advanced_title");document.getElementById("message-current-status").innerHTML=chrome.i18n.getMessage("settings_current_status");document.getElementById("message-sync-now").value=chrome.i18n.getMessage("dialog_sync_now");document.getElementById("message-account").innerHTML=
chrome.i18n.getMessage("settings_account");document.getElementById("message-sync-types").innerHTML=chrome.i18n.getMessage("settings_sync_types");document.getElementById("subsection-account-userinfo").innerHTML=chrome.i18n.getMessage("settings_not_logged_in");document.getElementById("subsection-account-authenticate").value=chrome.i18n.getMessage("dialog_sign_in");document.getElementById("message-run-wizard").value=chrome.i18n.getMessage("settings_run_wizard");document.getElementById("message-sync-options").innerHTML=
chrome.i18n.getMessage("settings_sync_options");document.getElementById("message-bookmarks").innerHTML=chrome.i18n.getMessage("settings_bookmarks");document.getElementById("message-tabs").innerHTML=chrome.i18n.getMessage("settings_tabs");document.getElementById("message-computer-name").innerHTML=chrome.i18n.getMessage("settings_computer_name");document.getElementById("message-auto-sync").innerHTML=chrome.i18n.getMessage("settings_auto_sync");document.getElementById("message-profiles-desc").innerHTML=
chrome.i18n.getMessage("settings_profiles_description");document.getElementById("message-create-and-manage").innerHTML=chrome.i18n.getMessage("settings_create_and_manage_profiles");document.getElementById("message-my-xmarks").value=chrome.i18n.getMessage("settings_my_xmarks");document.getElementById("message-change-profile").value=chrome.i18n.getMessage("settings_change_profile");document.getElementById("message-current-profile").innerHTML=chrome.i18n.getMessage("settings_current_profile");document.getElementById("message-restore-desc").innerHTML=
chrome.i18n.getMessage("settings_restore_description");document.getElementById("message-previous-sets").innerHTML=chrome.i18n.getMessage("settings_previous_sets");document.getElementById("restore-option-default").innerHTML=chrome.i18n.getMessage("settings_retrieving_list");document.getElementById("restore-preview").value=chrome.i18n.getMessage("settings_preview_bookmarks");document.getElementById("restore-bookmarks").value=chrome.i18n.getMessage("settings_restore_bookmarks");document.getElementById("message-connection-security").innerHTML=
chrome.i18n.getMessage("settings_connection_security");document.getElementById("message-encryption").innerHTML=chrome.i18n.getMessage("settings_encryption");document.getElementById("message-no-encryption").innerHTML=chrome.i18n.getMessage("settings_no_encryption");document.getElementById("message-login-only").innerHTML=chrome.i18n.getMessage("settings_login_only");document.getElementById("message-encrypt-all").innerHTML=chrome.i18n.getMessage("settings_encrypt_all");document.getElementById("message-manual-upload").innerHTML=
chrome.i18n.getMessage("settings_manual_upload");document.getElementById("message-force-upload").innerHTML=chrome.i18n.getMessage("settings_manual_upload_desc");document.getElementById("message-upload-bookmarks").value=chrome.i18n.getMessage("settings_upload_bookmarks");document.getElementById("message-manual-download").innerHTML=chrome.i18n.getMessage("settings_manual_download");document.getElementById("message-force-download").innerHTML=chrome.i18n.getMessage("settings_manual_download_desc");document.getElementById("message-download-bookmarks").value=
chrome.i18n.getMessage("settings_download_bookmarks");document.getElementById("message-logging").innerHTML=chrome.i18n.getMessage("settings_logging");document.getElementById("message-enable-logging").innerHTML=chrome.i18n.getMessage("settings_enable_logging");document.getElementById("logging-info").innerHTML=chrome.i18n.getMessage("settings_logging_info");document.getElementById("message-report-bug").innerHTML=chrome.i18n.getMessage("settings_report_bug");document.getElementById("message-recent-changes").innerHTML=
chrome.i18n.getMessage("settings_recent_changes");document.getElementById("message-close").value=chrome.i18n.getMessage("dialog_close");document.getElementById("version-string").innerHTML=chrome.i18n.getMessage("settings_version_string",["???"])}
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){HandleLoad()});document.getElementById("category-general").addEventListener("mouseover",function(){HighlightCategory(this)});document.getElementById("category-sync").addEventListener("mouseover",function(){HighlightCategory(this)});document.getElementById("category-profiles").addEventListener("mouseover",function(){HighlightCategory(this)});document.getElementById("category-advanced").addEventListener("mouseover",
function(){HighlightCategory(this)});document.getElementById("category-general").addEventListener("mouseout",function(){UnhighlightCategory(this)});document.getElementById("category-sync").addEventListener("mouseout",function(){UnhighlightCategory(this)});document.getElementById("category-profiles").addEventListener("mouseout",function(){UnhighlightCategory(this)});document.getElementById("category-advanced").addEventListener("mouseout",function(){UnhighlightCategory(this)});document.getElementById("subsection-types-bookmarks").addEventListener("change",
function(){HandleSyncTypeBookmarksChange()});document.getElementById("subsection-types-tabs").addEventListener("change",function(){HandleSyncTypeTabsChange()});document.getElementById("computer-name").addEventListener("change",function(){HandleComputerNameChange()});document.getElementById("encryption-setting").addEventListener("change",function(){HandleEncryptionChange(this)});document.getElementById("enable-logging").addEventListener("change",function(){HandleLoggingChange()});document.getElementById("subsection-options-autosync").addEventListener("change",
function(){HandleAutoSyncChange()});document.getElementById("category-general").addEventListener("click",function(){LoadCategory(this)});document.getElementById("category-sync").addEventListener("click",function(){LoadCategory(this)});document.getElementById("category-profiles").addEventListener("click",function(){LoadCategory(this)});document.getElementById("category-advanced").addEventListener("click",function(){LoadCategory(this)});document.getElementById("message-sync-now").addEventListener("click",
function(){TriggerAction("sync")});document.getElementById("subsection-account-authenticate").addEventListener("click",function(){ToggleAuth()});document.getElementById("message-run-wizard").addEventListener("click",function(){RunSetupWizard()});document.getElementById("message-my-xmarks").addEventListener("click",function(){VisitMyXmarks()});document.getElementById("message-change-profile").addEventListener("click",function(){ShowProfilesWindow()});document.getElementById("restore-preview").addEventListener("click",
function(){PreviewBookmarks()});document.getElementById("restore-bookmarks").addEventListener("click",function(){RestoreBookmarks()});document.getElementById("message-repair-bookmarks").addEventListener("click",function(){RepairNow("bookmarks")});document.getElementById("message-upload-bookmarks").addEventListener("click",function(){ConfirmUpload("bookmarks")});document.getElementById("message-download-bookmarks").addEventListener("click",function(){ConfirmDownload("bookmarks")});document.getElementById("message-close").addEventListener("click",
function(){window.close()})});
