function XmarksSettings(){this.LoadSettings()}XmarksSettings.VERSION="1.0.33";XmarksSettings.SERVER_ROOT="xmarks.com";
XmarksSettings.prototype={prefs:{},Get:function(a,b){return this.prefs.hasOwnProperty(a)?this.prefs[a]:b},GetInt:function(a,b){var c=this.Get(a,b);return parseInt(c)},GetBool:function(a,b){return"true"==this.Get(a,b)?!0:!1},Set:function(a,b,c){b=String(b);this.prefs[a]=b;c&&localStorage.setItem("pref-"+a,b)},Remove:function(a){delete this.prefs[a];localStorage.removeItem("pref-"+a)},SetWindowParams:function(a){this.windowParams=a},GetWindowParams:function(){var a=this.windowParams;delete this.windowParams;
return a},WindowSetChanged:function(a){var b=this.windowSet;if(!b)return!0;b=JSON.stringify(b);a=JSON.stringify(a);return b!=a},SaveWindowSet:function(a){this.windowSet=a},SetSyncInfo:function(a){this.syncInfo=a},GetSyncInfo:function(){return this.syncInfo},GetUserHash:function(){return this.prefs["current-username"]+"@"+this.prefs["server-root"]+"-"},GetBaseline:function(a){return this[this.GetUserHash()+"baseline"+a]},LoadLocalBaseline:function(a,b){function c(a){a.executeSql("SELECT * FROM '"+
f+"';",[],function(a,b){if(b&&b.rows)for(var c=0;c<b.rows.length;c++){var d=unescape(b.rows.item(c).data),d=new_node_from_source(d);j.AddNode(d)}})}function d(a){k.LogWrite("Error finding table ["+f+"]; no persisted baseline.  Error: "+a.message);b()}function g(){k.LogWrite("Success reading from db");k.SetBaseline(j,a.suffix,!1,b)}if(this.GetBaseline(a.suffix))b();else{var e=this.GetUserHash(),h=openDatabase(e+"baseline"+a.suffix,"","Baseline files for ["+e+"]",1);if(h){var k=this,f="rev-"+this.Get(e+
"rev"+a.suffix)+"-"+this.Get(e+"profileid",0)+a.suffix,e=new a.ds,j=new Nodeset(e);h.transaction(c,d,g)}else this.LogWrite("Unable to open baseline db!  No persisted baseline."),b()}},SetBaseline:function(a,b,c,d,g){function e(b){g&&b.executeSql("DROP TABLE '"+m+"';",[]);b.executeSql("CREATE TABLE '"+m+"' (rowId INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT);",[],function(b){function c(d){d=a.Node(d).toSource();d="INSERT INTO '"+m+"' ('data') VALUES ('"+escape(d)+"');";b.executeSql(d,[])}function d(){l.LogWrite("Baseline inserts complete")}
a&&a.OnTree(c,d)})}function h(a){l.LogWrite("Error dropping and creating table ["+m+"]; not saving new baseline.  Error: "+a.message);d&&d(-2)}function k(){l.LogWrite("Baseline stored in: "+m);l.RemoveBaselines(j,m,d)}var f=this.GetUserHash();this[f+"baseline"+b]=a;if(c){c=300;a&&(c=300*a.length);var j=openDatabase(f+"baseline"+b,"","Baseline files for ["+f+b+"]",c);if(j){var l=this,m="rev-"+this.Get(f+"rev"+b)+"-"+this.Get(f+"profileid",0)+b;j.transaction(e,h,k)}else this.LogWrite("Unable to open baseline db!  Cannot save user baseline."),
d&&d(-1)}else d&&d(0)},DeleteUserBaselineData:function(a,b){var c=this.GetUserHash()+"baseline"+a;this[c]=null;var d=openDatabase(c,"","Baseline files for ["+this.GetUserHash()+"]",300);d?this.RemoveBaselines(d,null,b):(this.LogWrite("Unable to open baseline database for "+c+", no saved baseline data to remove?"),b&&b(-1))},RemoveBaselines:function(a,b,c){function d(a){a.executeSql("SELECT name FROM sqlite_master WHERE type = 'table'",[],g)}function g(a,c){if(c&&c.rows)for(var d=0;d<c.rows.length;d++){var e=
c.rows.item(d).name;0==e.indexOf("rev-")&&e!=b&&a.executeSql("DROP TABLE '"+e+"';",[])}}function e(a){k.LogWrite("Error removing old baselines: "+a.message);c&&c(-2)}function h(){k.LogWrite("Old baselines removed");c&&c(0)}b||(b="dummyTableName");if(a){var k=this;a.transaction(d,e,h)}else this.LogWrite("No baseline db specified!  Cannot remove user baseline."),c&&c(-1)},GetUserSettings:function(){if(!this.Get("current-username"))return{username:null};var a=this.GetUserHash(),b={};b.username=this.Get(a+
"username",null);b.password=this.Get(a+"password",null);b.authtoken=this.Get(a+"authtoken",null);b.lastsync=this.Get(a+"lastsync",null);b.profilename=this.Get(a+"profilename",null);b.profileid=this.Get(a+"profileid",null);b.bookmarksrevision=this.Get(a+"rev",null);b.passwordsrevision=this.Get(a+"rev-passwords",null);return b},SetUserSettings:function(a){var b=a.remember;void 0==b&&(b=null==localStorage.getItem("pref-current-name"));if(a.username){this.Set("current-username",a.username,b);var c=Xmarks.Settings.GetUserHash();
this.Set(c+"username",a.username,b);this.Set(c+"password",a.password,b);this.Set(c+"authtoken",a.authtoken)}else this.Remove("current-username")},LoadSettings:function(){function a(a,b,c){a=a.split(".");b=b.split(".");for(var d=a.length>b.length?a.length:b.length,f=0;f<d&&!(c&&1<f);f++){var j=a.length>f?parseInt(a[f]):0,l=b.length>f?parseInt(b[f]):0;if(j>l)return-1;if(l>j)return 1}return 0}for(var b=0;b<localStorage.length;b++){var c=localStorage.key(b);0==c.indexOf("pref-")&&this.Set(c.substr(5),
localStorage.getItem(c))}this.Get("server-root")||this.Set("server-root",XmarksSettings.SERVER_ROOT);(b=this.Get("version"))?0>a(XmarksSettings.VERSION,b)&&(0!=a(XmarksSettings.VERSION,b,!0)&&this.Set("major-upgrade-run",!0),this.Set("version",XmarksSettings.VERSION,!0),this.Set("upgrade-run",!0)):(this.Set("version",XmarksSettings.VERSION,!0),this.Set("first-run",!0));var b=this.Get("server-root"),c={webserver:"www.",authserver:"login.",cloudserver:"cloud.",staticserver:"static.",syncserver:"sync."},
d;for(d in c)this.Get(d)||this.Set(d,c[d]+b)},GetMachineId:function(){var a=this.Get("machineId");a||(a=Date.now().toString(36),this.Set("machineId",a,!0));return a},LogWrite:function(a){if(!1==this.GetBool("disableLogging","false")){var b=new Date,c=b.getMonth()+1,d=b.getDate(),g=b.getFullYear(),e=b.getHours(),h=b.getMinutes();10>h&&(h="0"+h);b=b.getSeconds();10>b&&(b="0"+b);console.log("["+c+"/"+d+"/"+g+" "+e+":"+h+":"+b+"] "+a)}},GetPostSyncCallback:function(){return this._postSyncCallback},SetPostSyncCallback:function(a){this._postSyncCallback=
a}};function XmarksSingleton(){}
XmarksSingleton.prototype={Settings:new XmarksSettings,LogWrite:function(a){this.Settings.LogWrite(a)},GenerateNid:function(){var a="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.+".split("");XmarksSingleton.gNidCounter||(XmarksSingleton.gNidCounter=(new Date).getTime());XmarksSingleton.gNidCounter++;for(var b="",c=XmarksSingleton.gNidCounter;0<c;)b+=a[c&63],c>>>=6;return b},GetUserCredentials:function(a,b){function c(b,c){b.close();a(c)}this.LogWrite("Starting authentication");var d=
this.Settings.GetUserSettings();!b&&d.username&&d.password&&a&&"function"==typeof a?a(d):(b?this.Settings.SetWindowParams({forceRequest:b,callback:c,username:d.username}):this.Settings.SetWindowParams({forceRequest:b,callback:c,username:d.username,password:d.password}),this.ShowWindow("authdialog.html","xmarksAuthDialog",200,400))},VerifyUserPin:function(a,b){this.LogWrite("Getting PIN from user");this.Settings.SetWindowParams({callback:function(b,d){b.close();a(d)},pinConfirmCallback:b});this.ShowWindow("pindialog.html",
"xmarksPinDialog",200,450)},ShowDialog:function(a,b,c,d,g,e){g||(g=170);e||(e=400);b||(b={});b.button1||(b.button1="Ok");this.Settings.SetWindowParams({message:a,callback:function(a,b){a.close();c&&"function"==typeof c&&(d&&"object"==typeof d?c.call(d,b):c(b))},buttons:b});this.ShowWindow("popupdialog.html","xmarksPopupDialog",g,e)},ShowWindow:function(a,b,c,d){a=window.open(a,b,"height="+c+",width="+d+",left="+(window.screen.width-d)/2+",top="+(window.screen.height-c)/2+"toolbar=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,location=no");
a.focus();return a},IsValidChromeBookmark:function(a){if(!a)return!1;a=a.trim();if(""==a||"data:"==a.substr(0,5))return!1;var b=a.indexOf("://");return!a.substring(b+3)?!1:!0},ExtractProtocolAndDomain:function(a){if(!a)return null;var b=a.indexOf("://");if(0>b)return null;b=a.indexOf("/",b+3);return 0>b?a:a.substr(0,b)},HasProtocol:function(a){var b=a.indexOf("."),c=a.indexOf("/");a=a.indexOf(":");var d=0<a;d&&(0<=b&&b<a?d=!1:0<=c&&c<a&&(d=!1));return d},GetRequestArgs:function(a){a||(a={});a.manual=
!1==this.Settings.GetBool("auto-sync","false");a.log={mid:this.Settings.GetMachineId()};var b=this.Settings.GetUserHash(),b=this.Settings.GetInt(b+"profileid",0);0!=b&&(a.view=b);0<this.Settings.GetInt("failcount",0)&&(a.retry=this.Settings.GetInt("failcount",0));return a}};var Xmarks=new XmarksSingleton;
